server:
  port: 8086

spring:
  datasource:
    username: root
    password: 1999
    url: jdbc:mysql://localhost:3306/601_server?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver